// Generates CREDITS.md from the one credits list (catalog/credits.ts), which also feeds the in-game Credits screen.
import { writeFileSync } from 'node:fs';
import { CREDITS } from '../catalog/credits';

const rows = CREDITS.map((c) => `| ${c.what} | ${c.author} | ${c.license} | ${c.url} |`).join('\n');
writeFileSync(
  'CREDITS.md',
  `# Credits

Generated by \`npm run credits\` from \`catalog/credits.ts\` — edit that file, not this one.

| What | Author | Licence | Source |
|---|---|---|---|
${rows}
`,
);
console.log('CREDITS.md written');
